-- +goose Up
CREATE SCHEMA IF NOT EXISTS users;
CREATE SCHEMA IF NOT EXISTS betting;
CREATE SCHEMA IF NOT EXISTS payments;
CREATE SCHEMA IF NOT EXISTS odds;
CREATE SCHEMA IF NOT EXISTS notifications;
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- +goose Down
DROP SCHEMA IF EXISTS notifications CASCADE;
DROP SCHEMA IF EXISTS odds CASCADE;
DROP SCHEMA IF EXISTS payments CASCADE;
DROP SCHEMA IF EXISTS betting CASCADE;
DROP SCHEMA IF EXISTS users CASCADE;